version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "password123"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pguser"
      PGADMIN_DEFAULT_PASSWORD: "password123"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "80:80"
    networks:
      - postgres
    restart: unless-stopped

  seekh:
    depends_on:
      - postgres
    build: .
    ports:
      - "5000:5000"
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
